### ISSUE TITLE
can't work

### ISSUE THREAD

**Issue by ChaosTong** [LiuRoy/huatian-funny#3]
Traceback (most recent call last):
  File "./spider.py", line 82, in <module>
    search()
  File "./spider.py", line 76, in search
    users = response.json()['list']
KeyError: 'list'

**Comment by LiuRoy** [comment]
@ChaosTong 我猜是因为没有登陆成功，可能的原因是LOGIN_HEADER中的Cookie过期了，这个Cookie是由js生成用来标注客户端的，你可以用浏览器抓一下请求，把Cookie重写一下。当然用户名和密码也得配置正确。

**Comment by ChaosTong** [comment]
是的，重写LOGIN_HEADERS，设置成自己的相关设置就OK了。
